export const SET_TOKEN = 'SET_TOKEN';
export const GET_TOKEN = 'GET_TOKEN';
export const RESET_TOKEN = 'RESET_TOKEN';

export const ADD_ALBUMSEARCHED = 'ADD_ALBUMSEARCHED';
export const GET_ALBUMSSEARCHED = 'GET_ALBUMSSEARCHED';

export const SET_SEARCHING = 'SET_SEARCHING';
export const RESET_SEARCHING = 'RESET_SEARCHING';